{
 "title": "Services statistic",
 "time": { "from": "2021-11-20T17:22:00.237Z", "to": "2021-11-20T17:40:55.296Z" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "Average test duration by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(test_duration_fail_seconds_sum{}[1m])) by (service) / sum by (service) (increase(test_duration_fail_seconds_count{}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Tests info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Tests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(test_duration_ok_seconds_count{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}} - success"
    },
    {
     "expr": "sum(increase(test_duration_fail_seconds_count{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}} - fail"
    }
   ]
  },
  {
   "title": "Success percent (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(test_duration_ok_seconds_count{service=\"$service\"}[1m]) / (increase(test_duration_ok_seconds_count{service=\"$service\"}[1m]) + increase(test_duration_fail_seconds_count{service=\"$service\"}[1m]))",
     "legendFormat": "{{service}} - success"
    }
   ]
  },
  {
   "title": "Test duration quantile 95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "test_duration_ok_seconds{service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{service}} - success"
    },
    {
     "expr": "test_duration_fail_seconds{service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{service}} - fail"
    }
   ]
  },
  { "title": "Stages info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Success stages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(stage_duration_ok_seconds_count{service=\"$service\"}[1m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Fail stages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(stage_duration_fail_seconds_count{service=\"$service\"}[5m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Success stages quantile 95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stage_duration_ok_seconds{service=\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{stage}}"
    },
    {}
   ]
  },
  {
   "title": "Fail stages quantile 95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stage_duration_fail_seconds{service=\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{stage}}"
    },
    {}
   ]
  },
  { "title": "Http calls info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Http requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_external_duration_seconds_count{service=\"$service\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http requests quantile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(http_external_duration_seconds{service=\"$service\", quantile=\"0.95\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http response per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_external_duration_seconds_count{service=\"$service\"}[1m])) by (method,code)",
     "legendFormat": "{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "Executors info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queued jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      { "expr": "executor_queue_length" }
     ]
    },
    {
     "title": "Running jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      { "expr": "executor_run_jobs" }
     ]
    }
   ]
  }
 ]
}